### ISSUE TITLE
Event recorder reports

### ISSUE THREAD

**Issue by docterry** [pedcards/TRRIQ#13]

**Comment by docterry** [comment]
> The easiest way to deal with this on the DB side is to create one .csv that has the same dataset for each of these test regardless of test type, which will have null or blank values for terms that are not relevant to the particular test. For example, all .csv forms will have a field “Number_of_transmissions”, but for only Event recorders will it have a value associated with it. Does that make sense? Would that work on your end? 
> Steve
>
> How would the database handle having a mix of Holters and Event recorders (and Zio patch reports, for that matter) in the Holter PDFs folder? We could give them a different name or different CSV name.
> -TC

**Comment by pedcards** [comment]
MicroER 4X = nonloop
CG-6106 Explorer 4X = looping
